name: Matrix Strategy Example

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runtime:
          - npm
          - maven
          - pip

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine runtime from commit message
        id: runtime_selection
        run: |
          if [[ "${{ github.event.head_commit.message }}" == npm* ]]; then
            echo "::set-output name=runtime::npm"
          elif [[ "${{ github.event.head_commit.message }}" == maven* ]]; then
            echo "::set-output name=runtime::maven"
          elif [[ "${{ github.event.head_commit.message }}" == pip* ]]; then
            echo "::set-output name=runtime::pip"
          else
            echo "::error::Unsupported runtime specified in commit message"
            exit 1
          fi

      - name: Set up ${{ steps.runtime_selection.outputs.runtime }} environment
        if: steps.runtime_selection.outputs.runtime == matrix.runtime
        run: echo "Setting up ${{ steps.runtime_selection.outputs.runtime }} environment"

      - name: Build and test with ${{ steps.runtime_selection.outputs.runtime }}
        if: steps.runtime_selection.outputs.runtime == matrix.runtime
        run: |
          if [ "${{ steps.runtime_selection.outputs.runtime }}" = "npm" ]; then
            npm install
            npm test
          elif [ "${{ steps.runtime_selection.outputs.runtime }}" = "maven" ]; then
            mvn clean install
          elif [ "${{ steps.runtime_selection.outputs.runtime }}" = "pip" ]; then
            pip install -r requirements.txt
            pytest
          fi
